/*
 * TapIn PAM Module
 * Provides passwordless authentication via Bluetooth fingerprint verification
 * 
 * This module checks for a valid authentication token generated by the
 * TapIn mobile application after successful fingerprint verification.
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <sys/file.h>
#include <fcntl.h>
#include <time.h>
#include <security/pam_appl.h>
#include <security/pam_modules.h>
#include <security/pam_ext.h>

#define TOKEN_FILE "/var/run/tapin_auth.token"
#define MAX_LINE_LENGTH 256
#define TOKEN_EXPIRY_SECONDS 20

// Structure to hold token data
typedef struct {
    char username[64];
    char token[64];
    time_t expiry;
    int valid;
} token_data_t;

/*
 * Function to read and validate the authentication token
 */
static int read_auth_token(token_data_t *token) {
    FILE *file;
    char line[MAX_LINE_LENGTH];
    char *username, *token_str, *expiry_str;
    time_t current_time;
    
    // Check if token file exists and is readable
    if (access(TOKEN_FILE, R_OK) == -1) {
        return PAM_AUTH_ERR;
    }
    
    // Open the token file
    file = fopen(TOKEN_FILE, "r");
    if (!file) {
        return PAM_AUTH_ERR;
    }
    
    // Read the token line
    if (fgets(line, sizeof(line), file) == NULL) {
        fclose(file);
        return PAM_AUTH_ERR;
    }
    
    // Immediately close the file and attempt to delete it (atomic read and delete)
    fclose(file);
    
    // Verify the file still exists (to prevent race conditions)
    struct stat token_stat;
    if (stat(TOKEN_FILE, &token_stat) != 0) {
        // File was already deleted by another process
        return PAM_AUTH_ERR;
    }
    
    // Try to open and lock the file for exclusive access
    int fd = open(TOKEN_FILE, O_RDONLY);
    if (fd == -1) {
        return PAM_AUTH_ERR;
    }
    
    // Attempt to lock the file to prevent concurrent access
    if (flock(fd, LOCK_SH | LOCK_NB) == -1) {
        close(fd);
        return PAM_AUTH_ERR; // Another process is already handling this token
    }
    
    // Re-read the file content while locked
    FILE *reopened_file = fdopen(fd, "r");
    if (!reopened_file) {
        close(fd);
        return PAM_AUTH_ERR;
    }
    
    // Read the token line again to make sure it's still valid
    if (fgets(line, sizeof(line), reopened_file) == NULL) {
        fclose(reopened_file);
        return PAM_AUTH_ERR;
    }
    
    // Close file but keep the fd open for the lock
    fclose(reopened_file);
    
    // Parse the line: username:token:expiry
    char temp_line[MAX_LINE_LENGTH];
    strncpy(temp_line, line, sizeof(temp_line) - 1);
    temp_line[sizeof(temp_line) - 1] = '\0';
    
    username = strtok(temp_line, ":");
    token_str = strtok(NULL, ":");
    expiry_str = strtok(NULL, ":");
    
    if (!username || !token_str || !expiry_str) {
        close(fd);
        return PAM_AUTH_ERR;
    }
    
    // Copy parsed values
    strncpy(token->username, username, sizeof(token->username) - 1);
    token->username[sizeof(token->username) - 1] = '\0';
    
    strncpy(token->token, token_str, sizeof(token->token) - 1);
    token->token[sizeof(token->token) - 1] = '\0';
    
    token->expiry = atol(expiry_str);
    token->valid = 1;
    
    // Check if token is expired
    time(&current_time);
    if (current_time > token->expiry) {
        // Token expired, remove it
        unlink(TOKEN_FILE);
        close(fd);
        return PAM_AUTH_ERR;
    }
    
    // Release the lock and close the file descriptor
    close(fd);
    
    return PAM_SUCCESS;
}

/*
 * Function to remove the token file after use (one-time use)
 */
static void consume_token() {
    unlink(TOKEN_FILE);
}

/*
 * PAM authentication function
 * This is the main entry point for PAM authentication
 */
PAM_EXTERN int pam_sm_authenticate(pam_handle_t *pamh, int flags, int argc, const char **argv) {
    const char *username;
    token_data_t token;
    int retval;
    
    // Get the username being authenticated
    retval = pam_get_user(pamh, &username, NULL);
    if (retval != PAM_SUCCESS) {
        return PAM_USER_UNKNOWN;
    }
    
    // Read and validate the authentication token
    retval = read_auth_token(&token);
    if (retval != PAM_SUCCESS) {
        // No valid token found, continue with other authentication methods
        return PAM_AUTH_ERR;
    }
    
    // Check if the token username matches the requested username
    if (strcmp(token.username, username) != 0) {
        // Token is for a different user
        consume_token(); // Consume the token anyway to prevent reuse
        return PAM_AUTH_ERR;
    }
    
    // Authentication successful
    // Consume the token so it can't be reused
    consume_token();
    
    return PAM_SUCCESS;
}

/*
 * PAM account management function
 * Used for account validation after authentication
 */
PAM_EXTERN int pam_sm_acct_mgmt(pam_handle_t *pamh, int flags, int argc, const char **argv) {
    return PAM_SUCCESS;
}

/*
 * PAM password management function
 * Not implemented for this module
 */
PAM_EXTERN int pam_sm_chauthtok(pam_handle_t *pamh, int flags, int argc, const char **argv) {
    return PAM_SERVICE_ERR;
}

/*
 * PAM session management function
 * Not implemented for this module
 */
PAM_EXTERN int pam_sm_open_session(pam_handle_t *pamh, int flags, int argc, const char **argv) {
    return PAM_SERVICE_ERR;
}

PAM_EXTERN int pam_sm_close_session(pam_handle_t *pamh, int flags, int argc, const char **argv) {
    return PAM_SERVICE_ERR;
}